version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
     - "5672:5672"
     - "15672:15672"
    
  student-registration-service:
    image: student-registration 
    container_name: student-registration 
    ports:
     - "8080:8080"
    
  student-id-service:
    image: student-id 
    container_name: student-id 

 
